### ISSUE TITLE
Primeira arte

### ISSUE THREAD

**Issue by hravaglia** [Overamigos/A-Dungeon-and-no-Dragon#1]
Eu não sabia em que sessão disso aqui mandar a arte pra vcs então fiz por aqui msm ja q geral foi dormir já. Tava pensando em fazer uma protagonista mulher pq sim, deu vontade kkkkkk e ja que ela vai adquirindo equipamentos e magias com o decorrer da gameplay eu quis que ela tivesse algo que sempre vai estar lá até o final do jogo, ai tive a ideia de colocar uma capa vermelha q estaria em todas as "roupinhas" que ela pegar durante a gameplay (em formatos diferentes mas que ela sempre estivesse lá tlg). Eu fiz um sprite da personagem "standing" e tava pensando em fazer a animação só da capa se mexendo quando ela tiver parada como se fosse o vento. Eu tbm tava vendo um jogo q descobri hoje e que eu achei muito lindo e boa a ideia deles de animação: o personagem tem menos detalhe e o ambiente tem mais detalhe ja q sao coisas quase 100% estáticas. Aí pros inimigos que existem mais em quantidade serão simples que nem a protagonista ja que terão mais animações e os Boss que são maiores e o ambiente eu coloco mais detalhes na arte, Segue o nome do jogo que eu vi e o link do meu sprite:
Jogo - Hyper Light Drifter
 Sprite - 
![2020-01-19 01_27_27-Window](https://user-images.githubusercontent.com/46460585/72674879-e2842480-3a5a-11ea-9af1-a0717ba1523b.png)

PS: Obviamente essa não é a versão final pq eu fiz sem consultar vcs sobre a estética, então depois a gente discute melhor sobre cores, proporções, etc.

**Comment by marcymon97** [comment]
Achei daora pakas a ideia, tenha em mente também que a gente vai precisar de um sprite sheet bem detalhado pras animações.
Eu fiz um primeiro commit com animação de idle e movimento e utilizei os sprite sheets abaixo como placeholder, seria uma boa você se guiar pela ideia deles.

https://github.com/Overamigos/A-Dungeon-and-no-Dragon/blob/feature/animation/assets/sprites/PlayerIdle.png

https://github.com/Overamigos/A-Dungeon-and-no-Dragon/blob/feature/animation/assets/sprites/PlayerRun.png

**Comment by hravaglia** [comment]
Brabo, salvou com isso aí pra ter uma base, vou usar sim.
